### PR TITLE
Update main.py

### PR DESCRIPTION
**Pull request by DavidSenpai**
Added help command correctly this time

### CODE REVIEW

**Comment by ijsbol** [comment]
ping command*
I'm not too versed with the delete_after attribute, is there a need for the Try & Except statements after line 60?

**Comment by DavidSenpai** [comment]
its removable but its in case something happens to the message (HTTPException or Notfound)

I havent had any issues with delete_after but im fine with removing

🐍 snek

**Comment by ijsbol** [comment]
Please could you add those specific exceptions to the Except statement instead of a generalised Except statement?

**Comment by ijsbol** [comment]
david qt pls

**Pull request closed without merging**
